//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCosmeticWAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Password { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string GroupID { get; set; }
        public Nullable<double> BaseSalary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Store Store { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
